### ISSUE TITLE
transfer back to your account

### ISSUE THREAD

**Issue by jeffreyjackson** [heyalexej/awesome-images#16]
hey @heyalexej we are going with a different direction on this.  So I will be moving this back to you.

**Comment by jeffreyjackson** [comment]
sound good?

**Comment by jeffreyjackson** [comment]
I am moving it around so you can accept it.  Please do when you get a chance.

**Comment by heyalexej** [comment]
Okay. WIll I get a notification or something?

**Comment by jeffreyjackson** [comment]
yeah you should

**Comment by jeffreyjackson** [comment]
do you see anything on this page? https://github.com/jeffreyjackson/awesome-images

**Comment by heyalexej** [comment]
nah, nothing out of the ordinary.

**Comment by jeffreyjackson** [comment]
trying again

![capture](https://cloud.githubusercontent.com/assets/867999/7073414/5f52d47a-dec1-11e4-8cd0-68a2bc755ada.PNG)

**Comment by jeffreyjackson** [comment]
check your email is what im reading

**Comment by heyalexej** [comment]
Cheers.

**Comment by jeffreyjackson** [comment]
:beers: :grimacing:
